E="";
Z=32.chr;
T=27.chr;
D=->k,d{c=35;k.scan(/../){c+=1;d.gsub!(c.chr,$&)};d};

include(Math);
M=D["MUSIC_K","MUSIC_S"].bytes;
F=44100;
z={};
H=->n,l,v{
  z[[n,l,v]]||=(
    l=(3e5/l).round;
    t=0;
    (0...l).map{|j|
      k=(j+1e3)%l/1e3;
      x=j*440*2**(n/12.0)/F*PI;
      sin(x+2*t=sin(x+t))*v*(k>4?1:(2-(3-k).abs).abs)/3
    }
  )
};
W="MHJEFAFH".bytes.flat_map{|n|H[n-84,6,32]}*29+H[-7,3,32];
i=v=0;
l=n=6;
(
  c=M.pop-98;
  c<0?v=c*3+32:(
    l=l*12/(2**(c%5)*3**(c/5));
    d=M.pop-93;
    d>0&&(
      j=i;
      H[n+=d-13,l,v].map{|t|
        W[j]+=t;
        W[j+4e5]+=t;
        W[j+8e5]+=t;
        j+=1
      }
    );
    i+=3e5/l
  )
)while(M!=[]);
Y=["data",W.size,*W.map{|c|c+128}].pack("A4VC*");
o=IO.popen($*[0]||"aplay#{Z}-q#{Z}-","wb");
o<<["RIFF",28+Y.size,"WAVEfmt"+Z,16,1,1,F,F,1,8].pack("A4VA8VvvVVvv")<<
Y.slice!(0,F);

L=D["LOGO_K","LOGO_S"].tr("a-z",Z+"#'()+,-./=@MTV_"<<92);
P=->s{[q="+---+"+Z*(6+s.size),"|:#{s}:SPONSORS",q]};
f=40;
c=E+R=D["COLOR_K","COLOR_S"];
S=[
  [
    "Abby:Phoenix-EXECUTIVE:ADMINISTRATOR",
    "Heather:Johnson-EVENT:PRODUCER",
    "Shirley:Bailes-SPONSORSHIP:CONSULTANT"
  ],
  [
    "Sarah:Mei#{t="-PROGRAM:"}CHAIR",
    "Evan:Phoenix"+t+="DIRECTOR",
    "Marty:Haught"+t,
  ],
  [
    "Akira:Matsuda"+t="-TRACK:DIRECTOR",
    "Coraline:Ada:Ehmke"+t,
    "Courteney:Ervin"+t,
  ],
  [
    "Derek:Prior"+t,
    "Nadia:Odunayo"+t,
    "Nickolas:Means"+t,
  ]
].map{|a|a.flat_map{|s|y,x=s.split(?-);[E]*5+[x+Z*x.size,Z*y.size+y]}[5..-1]};
S[1,0]=[p,"[[:Program:Committee:]]"];
e="%%";
i=-1;
[
  p,
  C.gsub(/./){Z==$&?c[i+=1].tr("]_`","##;"):Z}.lines[MARGIN,23],
  p,
  "<<-'#{A="RubyConf:2017"}':--:@New_Orleans.->>",
  p,
  "[[:Planning:Team:]]",
  *S,
  p,
  P[:DIAMOND],
  p,
  L.scan(/.{92}/)[0,7]+[E,"DigitalOcean"],
  p,
  P[:PLATINUM],
  p,
  L[644..-1].scan(/.{47}/)+[E,"EngineYard"],
  p,
  P[:GOLD],
  *[
    "STITCH:FIX-sqreen",
    "Braintree-HEROKU",
    "entelo-SENTRY",
    "DATADOG-ROOSTIFY"
  ].map{|a|
    f=40-f;
    a.split(?-).flat_map{|s|
      l=Z*f;
      r=Z*f=40-f;
      [E,E,l+s+r,l+?=*s.size+r,E,E]
    }
  },
  p,
  P[:BRONZE]+[E,"BRAKEMANPRO"]+
  [E]*4+
  P[:OTHER]+[E,"covermymeds",E,"Google:Cloud:Platform"],
  p,
  "All:speakers:and:attendants",
  p,
  "Brought:to:you:by:the:folks:at:Ruby:Central",
  p,
  A,
  p,
  [
    r=?%*39,
    u=e+Z*35+e,
    e+":::::Remember:this:is:a:Quine!:::::"+e,
    u,
    "%(:This:banner:is:a:valid:Ruby:code.:)%",
    u,
    r
  ],
  p,
  ["The:original:source:code:follows...",E,E,"---8<---"*8],
  p,
  C.gsub(/./){Z==$&?(c=R.slice!(0,1).ord;T+"[#{c-52}m#{Z+T}[0m"):$&}.lines
].flat_map{|s|
  (s)?(
    s=[*s];
    [E]+s.map{|l|l.center(99).rstrip}+[E]*[0,(23-s.size)/2].max+[p]
  ):[E]*24
}.map{|s|
  n=(s)?(
    puts(Z==s[0]?s.tr(?:,Z):s);
    1
  ):86;
  t=Time.new;
  o<<Y.slice!(0,4410*n);
  $$until(t+0.09*n<Time.now)
};
o<<Y;
o.close;
exit#...RubyConf.2017.Quine.(C).Yusuke.Endoh..
